-- REPO DIVER V10 BACKEND REFERENCE ONLY
-- DO NOT RUN THIS FILE. The V10 migrations have already been applied to Supabase project:
-- hvdrwmjieguurxvrgzfu
--
-- Live backend now contains:
--   18 repo_diver_biome_catalog rows
--   202 fish rows in repo_diver_catch_catalog
--   10 Ancient boss-scale fish
--   100 recipe rows
--   repo_diver_endgame_scores_2026
--   repo_diver_variant_logs_2026
--   repo_diver_career_2026.endgame / mastery persistence
--
-- Live RPCs added/updated:
--   repo_diver_submit_endgame_score(uuid,text,integer,integer,text)
--   repo_diver_get_endgame_leaderboard()
--   repo_diver_record_variants(uuid,jsonb)
--   repo_diver_craft_endgame_item(text)
--   repo_diver_get_career_state()
--
-- Endgame score submissions are duplicate-safe by run_id.
-- Crafted modules and salvage material balances are server-authoritative.
