-- REPO COMPANY V20.33 — TCG 167 CARD SYNC
-- Already applied to the live Supabase project. Included for source control.
-- Current catalogue = 167 unique cards:
--   156 normal-pack cards
--   1 One Week Anniversary LTD card
--   10 World Cup 2026 event cards
-- The nine Repo Sports Stars Full Art cards below were previously client-defined
-- but absent from the normal pack RPC. The live migration adds them to that pool
-- and updates collection RPC totals/merging to the canonical 167.

-- Added normal-pack IDs:
-- vardesh_pipsqueak_full_art
-- norveth_rocky_full_art
-- talune_soup_full_art
-- iskandar_besquelcher_full_art
-- sorevia_debbie_full_art
-- drazhen_dopey_dom_full_art
-- belros_jud_full_art
-- nambara_mad_rager_full_art
-- belros_nimbler_2000_full_art

-- Migration name applied live: tcg_complete_167_card_catalogue
