const fs=require('fs'),vm=require('vm');
global.window=global;global.localStorage={getItem(){return null},setItem(){}};
vm.runInThisContext(fs.readFileSync(__dirname+'/assets/repo-diver/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/assets/repo-diver/engine.js','utf8'),{filename:'engine.js'});
const D=global.RepoDiverData,E=global.RepoDiverEngine;
const game=fs.readFileSync(__dirname+'/assets/repo-diver/game.js','utf8');
const audio=fs.readFileSync(__dirname+'/assets/repo-diver/audio.js','utf8');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
let pass=0,fail=0;function t(name,fn){try{if(fn()===false)throw Error('false');console.log('PASS',name);pass++}catch(e){console.log('FAIL',name,e.message);fail++}}
const eq={tank:4,cargo:4,harpoon:4,suit:4,boost:3,sonar:4,lure:3,fins:3,salvage:3,pressure:3};
function run(b='shipgrave',extra={}){return E.createRun({biome:b,level:35,equipment:eq,boat:{sonar:3,crane:3},weather:'clear',timeOfDay:'day',graphics:'high',specialistTools:['cutter','scanner','lift_bag'],...extra})}
t('V14 defines 36 authored sites',()=>D.EXPLORATION_LOCATIONS.length===36);
t('V14 defines 72 archaeology artifacts',()=>D.ARCHAEOLOGY_ARTIFACTS.length===72);
t('Six specialist exploration tools exist',()=>D.EXPLORATION_TOOLS.length===6);
t('Every biome has two authored sites',()=>D.BIOMES.every(b=>D.locationsForBiome(b.id).length===2));
t('Every authored site has five sequential chambers',()=>D.EXPLORATION_LOCATIONS.every(l=>l.rooms.length===5&&l.rooms[0].tool==='none'));
t('All artifact definitions point at real sites',()=>D.ARCHAEOLOGY_ARTIFACTS.every(a=>!!D.locationById(a.location_id)));
t('Each site has two artifact definitions',()=>D.EXPLORATION_LOCATIONS.every(l=>D.artifactsForLocation(l.id).length===2));
t('Artifacts are gated to deep site stages',()=>D.ARCHAEOLOGY_ARTIFACTS.every(a=>[4,5].includes(Number(a.stage))));
t('Run creates the two physical biome sites',()=>{const r=run();return r.sites.length===2&&r.sites.every(s=>s.biome==='shipgrave')});
t('Run specialist loadout is capped at three',()=>{const r=run('shipgrave',{specialistTools:['cutter','scanner','lift_bag','repair','dive_line']});return r.specialistTools.length===3});
t('Authored mission target survives createRun',()=>run('shipgrave',{missionLocationId:'crown_of_varn'}).missionLocationId==='crown_of_varn');
t('Interior state is available without breaking open-water state',()=>{const r=run();return r.interior===null&&r.openWorldState===null});
t('Game requests server archaeology state',()=>game.includes("repo_diver_get_exploration_state"));
t('Game uses server-backed discovery RPC',()=>game.includes("repo_diver_discover_location"));
t('Game uses sequential stage RPC',()=>game.includes("repo_diver_advance_location"));
t('Game uses server-backed artifact recovery',()=>game.includes("repo_diver_recover_artifact"));
t('Game uses Marine Institute identification RPC',()=>game.includes("repo_diver_identify_artifact"));
t('In-world site renderer exists',()=>game.includes('function drawMajorSites('));
t('Distinct authored interior renderer exists',()=>game.includes('function drawInterior('));
t('Normal E salvage remains as fallback',()=>game.includes("if(!interactExploration())E.interact(run, profile.equipment)"));
t('Specialist loadout UI enforces three tools',()=>game.includes('specialistTools.length<3'));
t('Marine Journal exposes archaeology ledger',()=>game.includes('archaeologyMarkup()'));
t('V14 location audio cues are implemented',()=>audio.includes("case 'location_enter'")&&audio.includes("case 'mechanism'")&&audio.includes("case 'artifact'"));
t('No continuous white-noise bed is called',()=>{const calls=[...audio.matchAll(/loopNoise\s*\(/g)].length;return calls===1});
t('V14 cache bust is on all five Repo Diver assets',()=>((html.match(/repo-diver-v14-authored-expeditions-20260815-1623/g)||[]).length===5));
t('Dive help now describes E as interact/salvage',()=>html.includes('E INTERACT / SALVAGE'));
t('Site types cover wrecks caves ruins and facilities',()=>new Set(D.EXPLORATION_LOCATIONS.map(x=>x.type)).size===4);
t('Major named campaign locations are present',()=>['frozen_longship','crown_of_varn','choir_vault','station_erebos','palace_of_tides','icebound_fleet'].every(id=>!!D.locationById(id)));
console.log(`RESULT ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
