const fs=require('fs'),vm=require('vm');
global.window=global;global.localStorage={getItem(){return null},setItem(){}};
vm.runInThisContext(fs.readFileSync(__dirname+'/assets/repo-diver/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/assets/repo-diver/engine.js','utf8'),{filename:'engine.js'});
const D=global.RepoDiverData,E=global.RepoDiverEngine;
const game=fs.readFileSync(__dirname+'/assets/repo-diver/game.js','utf8');
const audio=fs.readFileSync(__dirname+'/assets/repo-diver/audio.js','utf8');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const css=fs.readFileSync(__dirname+'/assets/repo-diver/repo-diver.css','utf8');
let pass=0,fail=0;function t(n,fn){try{if(fn()===false)throw Error('false');console.log('PASS',n);pass++}catch(e){console.log('FAIL',n,e.message);fail++}}
const eq={tank:4,cargo:4,harpoon:4,suit:4,boost:3,sonar:4,lure:3,fins:3,salvage:3,pressure:3};
function make(diff=null){return E.createRun({biome:'midnight',level:40,equipment:eq,boat:{sonar:4,crane:3},weather:'clear',timeOfDay:'day',graphics:'balanced',modifier:'rough_current',masterDifficulty:diff})}
t('Build marker identifies V16',()=>game.includes("__REPO_DIVER_BUILD__='v16-living-postgame-20260815'"));
t('V16 data exposes postgame rank metadata',()=>D.POSTGAME_RANKS?.length===6&&D.POSTGAME_RANKS[5].name==='VELMORAN MASTER');
t('V16 data exposes three Master difficulty labels',()=>D.MASTER_DIFFICULTIES?.map(x=>x.id).join(',')==='veteran,master,abyssal');
t('Legacy Hall exists physically in harbour',()=>html.includes('class="rd-hub-building legacy-hall locked"')&&html.includes('REPO DIVER<br>LEGACY HALL'));
t('Legacy nav and panel exist',()=>html.includes('data-hub-action="legacy"')&&html.includes('id="rdLegacyPanel"')&&html.includes('id="rdLegacy"'));
t('Frontend loads server-authoritative postgame state',()=>game.includes("repo_diver_get_postgame_state"));
t('Frontend loads server-authoritative crew epilogues',()=>game.includes("repo_diver_get_crew_epilogues"));
t('Master Expedition start is server validated',()=>game.includes("repo_diver_begin_master_expedition"));
t('Current-run Master site checkpoint is server recorded',()=>game.includes("repo_diver_master_checkpoint")&&game.includes("p_event:'site_entered'"));
t('Master completion uses claimed-run server finalizer',()=>game.includes("repo_diver_finalize_master_expedition"));
t('Daily and weekly Master leaderboard UI is present',()=>game.includes('rdV16DailyBoard')&&game.includes('rdV16WeeklyBoard')&&game.includes('repo_diver_get_master_leaderboard'));
t('Master Expedition grade/renown presentation exists',()=>game.includes('MASTER EXPEDITION COMPLETE')&&game.includes('DIVER RENOWN'));
t('No Master Expedition GP payout was added client-side',()=>!game.includes('MASTER GP REWARD')&&!game.includes('RENOWN COINS'));
t('Difficulty is passed into the engine',()=>game.includes('masterDifficulty:masterConfig?.difficulty||null'));
t('Engine stores Master difficulty',()=>{const r=make('master');return r.masterDifficulty==='master'});
t('Master difficulty raises oxygen pressure without HP inflation',()=>{const a=make(null),b=make('abyssal');a.ecology.current.strength=b.ecology.current.strength=0;E.update(a,1,{},{...eq});E.update(b,1,{},{...eq});return b.player.o2<a.player.o2&&b.player.hp===a.player.hp});
t('Abyssal rough current has additional physical risk',()=>E.update.toString().includes('masterCurrent')&&E.update.toString().includes("run.masterDifficulty==='abyssal'"));
t('Master photography HUD counts current-run photos',()=>game.includes('run.masterPhotoCount')&&game.includes('run.masterPhotoCount=Number(run.masterPhotoCount||0)+1'));
t('Living postgame has six Renown rank thresholds',()=>game.includes('VETERAN DIVER')&&game.includes('VELMORAN MASTER')&&game.includes('7500'));
t('Velmoran Ocean Atlas is rendered as category cards',()=>game.includes('VELMORAN OCEAN ATLAS')&&game.includes('rd-v16-atlas-grid')&&game.includes('atlasCard'));
t('Secret completion remains hidden until found',()=>game.includes("secrets:{current:postgameSecretCount(),total:5,hidden:true}")&&game.includes('UNDISCOVERED THREADS REMAIN'));
t('100 percent career claim uses a server validator',()=>game.includes('repo_diver_claim_velmoran_legend')&&game.includes('CLAIM 100% CAREER LEGACY'));
t('Legacy Hall automatically displays campaign and career trophies',()=>game.includes('rd-v16-campaign-case')&&game.includes('legacyTrophyMarkup'));
t('Veteran display decorations from crew/research rewards can populate the hall',()=>game.includes("slot:'decor'")&&game.includes('VETERAN DISPLAY'));
t('Tideline veteran interior has five interactable compartments',()=>['bridge','sonar','lab','galley','rack'].every(x=>game.includes(`data-rd-tideline-room=\\"${x}\\"`)||game.includes(`data-rd-tideline-room="${x}"`)));
t('Tideline interior interactions have contextual descriptions',()=>game.includes('function tidelineRoomInfo(')&&game.includes('SONAR STATION')&&game.includes('TROPHY WALL'));
t('Vessel cosmetics remain cosmetic presentation',()=>game.includes('VETERAN VESSEL CUSTOMISATION')&&game.includes('Cosmetic only · no stat creep'));
t('Crew epilogues render sequenced operation progress',()=>game.includes('crewEpilogueFor')&&game.includes('EPILOGUE ${Number(q.step||1)}/3'));
t('Crew epilogue claiming is server-authoritative',()=>game.includes('repo_diver_claim_crew_epilogue'));
t('All seven Deep Signal core crew remain in postgame',()=>D.CAMPAIGN_CREW?.length===7&&['darro','lyra','orin','ivar','cass','sella','mara'].every(id=>D.CAMPAIGN_CREW.some(x=>x.id===id)));
t('Postgame NPC dialogue changes after the campaign',()=>game.includes('POSTGAME_CREW_LINES')&&game.includes('POSTGAME CREW'));
t('Long-form Marine Institute projects are presented',()=>game.includes('LONG-TERM RESEARCH PROJECTS')&&game.includes('repo_diver_claim_postgame_project'));
t('Fish House gets recurring Legacy Service nights',()=>game.includes('legacyNight:postgameUnlocked()')&&game.includes('LEGACY SERVICE'));
t('Fish House Legacy nights do not add a new payout path',()=>!game.includes('legacyNightBonus')&&!game.includes('legacyGp'));
t('Own career profile exposes living postgame summary',()=>game.includes('rd-v16-profile-legacy')&&game.includes('OPEN LEGACY HALL'));
t('Public profile can expose postgame Renown and Master stats',()=>game.includes('rd-v16-public-legacy')&&game.includes('master_expeditions')&&game.includes('tournament_wins'));
t('Public profile privacy UI is preserved',()=>game.includes('repo_diver_set_public_profile')&&game.includes('MAKE PROFILE PRIVATE'));
t('Career timeline distinguishes unknown historical dates',()=>game.includes('PRE-LEGACY RECORD')&&game.includes('YOUR REPO DIVER TIMELINE'));
t('The campaign completion monument is present',()=>game.includes('THE DEEP SIGNAL<br>EXPEDITION')&&game.includes('BELOW THE CHARTS'));
t('Legacy Hall responsive styles are present',()=>css.includes('.rd-v16-hall-room')&&css.includes('.rd-v16-trophy-grid')&&css.includes('.rd-v16-master-grid'));
t('New epilogue and Master board styles are present',()=>css.includes('.rd-v16-epilogue')&&css.includes('.rd-v16-master-boards'));
t('Veteran public profile styling is present',()=>css.includes('.rd-v16-public-legacy')&&css.includes('.rd-v16-profile-legacy'));
t('V16 short reward audio cues exist',()=>audio.includes("case 'legacy_unlock'")&&audio.includes("case 'renown'"));
t('No continuous white-noise loop is invoked',()=>[...audio.matchAll(/loopNoise\s*\(/g)].length===1);
t('All five Repo Diver frontend assets are V16 cache-busted',()=>((html.match(/repo-diver-v16-living-postgame-20260815/g)||[]).length===5));
t('TCG Patch cache bust survives V16',()=>html.includes('script.js?v=tcg-patch-cards-20260815-v1'));
t('V15 Deep Signal remains present',()=>D.DEEP_SIGNAL_MISSIONS?.length===25&&game.includes('repo_diver_begin_campaign_mission'));
t('V14 archaeology remains present',()=>D.EXPLORATION_LOCATIONS?.length===36&&D.ARCHAEOLOGY_ARTIFACTS?.length===72);
t('V13 Living Ocean remains present',()=>!!D.ECOLOGY_ZONES&&!!E.createRun&&game.includes('repo_diver_record_ecology_observation'));
t('V12 Shared Ocean remains present',()=>game.includes('repo_diver_get_shared_world')&&game.includes('repo_diver_publish_catches'));
console.log(`RESULT ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
