const fs=require('fs'),vm=require('vm');
global.window=global;global.localStorage={getItem(){return null},setItem(){}};
vm.runInThisContext(fs.readFileSync(__dirname+'/assets/repo-diver/data.js','utf8'),{filename:'data.js'});
vm.runInThisContext(fs.readFileSync(__dirname+'/assets/repo-diver/engine.js','utf8'),{filename:'engine.js'});
const D=global.RepoDiverData,E=global.RepoDiverEngine;
const game=fs.readFileSync(__dirname+'/assets/repo-diver/game.js','utf8');
const audio=fs.readFileSync(__dirname+'/assets/repo-diver/audio.js','utf8');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const css=fs.readFileSync(__dirname+'/assets/repo-diver/repo-diver.css','utf8');
let pass=0,fail=0;function t(name,fn){try{if(fn()===false)throw Error('false');console.log('PASS',name);pass++}catch(e){console.log('FAIL',name,e.message);fail++}}
const ms=D.DEEP_SIGNAL_MISSIONS||[];
t('V15 campaign defines 25 missions',()=>ms.length===25);
t('V15 campaign defines five acts',()=>D.DEEP_SIGNAL_ACTS?.length===5);
t('V15 defines 12 story artifacts',()=>D.CAMPAIGN_ARTIFACTS?.length===12);
t('All site campaign missions point at real V14 sites',()=>ms.filter(m=>m.location_id).every(m=>!!D.locationById(m.location_id)));
t('Campaign spans all five acts',()=>[1,2,3,4,5].every(a=>ms.some(m=>m.act===a)));
t('Station Erebos is expanded to seven campaign checkpoints',()=>D.campaignMission('silence_at_erebos')?.stage_count===7);
t('Final depth expedition targets 420m',()=>D.campaignMission('below_charted_depths')?.min_depth===420);
t('Finale targets 520m',()=>D.campaignMission('the_deep_signal')?.min_depth===520);
t('Finale is not implemented as biome 19',()=>!D.BIOMES.some(b=>b.id==='below_charted_depths'||b.id==='deep_signal'));
t('Final bespoke visual zone exists only as campaign presentation data',()=>D.DEEP_SIGNAL_FINAL_ZONE?.id==='below_charted_depths');
t('Campaign core crew has at least six recurring cast members',()=>D.CAMPAIGN_CREW?.length>=6);
t('Cass remains a campaign rival',()=>D.campaignCrew('cass')?.role==='Rival Diver');
t('Game loads server campaign state',()=>game.includes("repo_diver_get_campaign_state"));
t('Game starts missions through server validation',()=>game.includes("repo_diver_begin_campaign_mission"));
t('Game records ordered server checkpoints',()=>game.includes("repo_diver_campaign_checkpoint"));
t('Game finalizes depth/finale after claimed run',()=>game.includes("repo_diver_finalize_campaign_run"));
t('Campaign launch preserves authored V14 locations',()=>game.includes('startDive(m.biome,loc,m.id,replay)'));
t('Existing completed sites can catch up campaign state',()=>game.includes('function catchUpCampaignSite('));
t('Archive replay explicitly disables duplicate campaign progression',()=>game.includes('run.campaign?.replay')&&game.includes('NO DUPLICATE PROGRESSION REWARDS'));
t('Campaign dive loop has live stage progression',()=>game.includes('function updateCampaignDive(dt)'));
t('Finale requires a sonar interaction for final client checkpoint',()=>game.includes('sonarBaseline')&&game.includes('THE SOURCE ANSWERED'));
t('Erebos has an observation-window setpiece',()=>game.includes('OBSERVATION DOME · EXTERNAL CONTACT'));
t('Finale draws a bespoke deep-water setpiece',()=>game.includes('function drawCampaignSetpiece(')&&game.includes('UNCHARTED DEPTHS'));
t('Rival Cass can appear physically in campaign water',()=>game.includes('CASS ROOK · FIELD RIVAL'));
t('Campaign mission objective HUD exists',()=>html.includes('id="rdCampaignObjective"')&&css.includes('.rd-campaign-objective'));
t('Short radio dialogue UI exists',()=>html.includes('id="rdCampaignRadio"')&&game.includes('function campaignRadio('));
t('Campaign has a dedicated premium harbour panel',()=>html.includes('id="rdCampaignPanel"')&&html.includes('data-hub-action="campaign"'));
t('Evidence board and crew UI are implemented',()=>game.includes('rd-campaign-evidence')&&game.includes('rd-campaign-crew-grid'));
t('Mission archive supports replay',()=>game.includes('data-rd-campaign-replay'));
t('Story assist only changes presentation hints',()=>html.includes('id="rdStoryAssist"')&&game.includes('settings.storyAssist'));
t('Fish House has post-expedition crew table presentation',()=>game.includes('rd-campaign-crew-table')&&game.includes('repoDiverCampaignCelebrated'));
t('Campaign completion trophy appears on career profile',()=>game.includes('rd-campaign-profile-trophy')&&game.includes('BELOW THE CHARTS'));
t('Campaign audio cues exist',()=>['radio','campaign_reveal','deep_signal','campaign_complete'].every(k=>audio.includes(`case '${k}'`)));
t('No continuous white-noise loop is invoked',()=>[...audio.matchAll(/loopNoise\s*\(/g)].length===1);
t('V15 cache bust is on all five Repo Diver assets',()=>((html.match(/repo-diver-v15-deep-signal-20260815-v1/g)||[]).length===5));
t('TCG Patch cache bust survives the Repo Diver update',()=>html.includes('script.js?v=tcg-patch-cards-20260815-v1'));
t('V14 archaeology remains present',()=>D.EXPLORATION_LOCATIONS.length===36&&D.ARCHAEOLOGY_ARTIFACTS.length===72);
t('V13 ecology remains present',()=>!!D.ECOLOGY_ZONES&&!!E.createRun);
t('V12 Shared Ocean calls remain present',()=>game.includes('repo_diver_get_shared_world')&&game.includes('repo_diver_publish_catches'));
t('Build marker identifies V15',()=>game.includes("__REPO_DIVER_BUILD__='v15-the-deep-signal-20260815'"));
console.log(`RESULT ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
