const fs=require('node:fs');
const assert=require('node:assert/strict');
const {init,seed,call,a,b,c}=require('./game-mode.cjs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const migration=fs.readFileSync(root+'/supabase/migrations/20260927010000_reparty_soundtrack.sql','utf8');
async function setup(){const pg=await init();await pg.exec(fs.readFileSync(root+'/supabase/migrations/20260926010000_reparty_suno_queue.sql','utf8'));await pg.exec(migration);await seed(pg);return pg;}
async function test(){
 const pg=await setup();let checks=0;
 const ok=(value,label)=>{assert.ok(value,label);checks++;console.log('PASS '+label);};
 const action=(user,name,room,data)=>call(pg,user,'reparty_action',name,room,data);
 const room=(await action(a,'create',null,{name:'Soundtrack QA'})).id;await action(b,'join',room);
 for(let i=0;i<12;i++)await pg.query(`insert into reparty_private.soundtracks values($1,'game','Old School RuneScape','Sea Shanty 2','Ian Taylor',2007,1,'["Old School RuneScape","RuneScape","OSRS","Sea Shanty 2"]',$2,0)`,['qa-'+i,'abcdefghij'+(i%10)]);
 let g;const quiz=async(user,name,data={})=>{const s=await call(pg,user,'reparty_soundtrack_action',name,room,{revision:g?.revision,token:g?.token,...data});g=s.room.settings.soundtrack;return s;};
 const expire=()=>pg.query(`update reparty_private.soundtrack_sessions set state=jsonb_set(state,'{deadline}',to_jsonb((clock_timestamp()-interval '1 second')::text)) where room_id=$1`,[room]);
 const answerPhase=async()=>{await quiz(a,'ready');await quiz(b,'ready');assert.equal(g.phase,'countdown');await expire();await quiz(a,'tick');assert.equal(g.phase,'guess');};
 await pg.query(`update public.reparty_rooms set playback='{"video_id":"abcdefghijk","item_id":"v1","playing":true,"position":42,"updated_at":"${new Date().toISOString()}"}' where id=$1`,[room]);
 const before=(await action(a,'snapshot',room)).room.playlists;
 let s=await quiz(a,'enter');ok(g.phase==='setup'&&s.room.settings.game.mode==='soundtrack'&&!s.room.playback.playing&&s.room.playback.position>=42,'enter freezes existing watch queue');
 await assert.rejects(quiz(c,'enter'),/Join this room/);checks++;
 await assert.rejects(call(pg,null,'reparty_soundtrack_action','enter',room),/sign in/i);checks++;
 const start=mode=>quiz(a,'start',{mode,category:'game',seconds:15,rounds:10,difficulty:2,players:[{id:a,team:'1'},{id:b,team:mode==='teams'?'2':'1'}]});
 await assert.rejects(quiz(b,'start'),/host/);checks++;
 await start('versus');ok(g.phase==='loading'&&g.total===10,'start draws unique recordings');
 let privateState=(await pg.query('select state from reparty_private.soundtrack_sessions where room_id=$1',[room])).rows[0].state;
 const ids=(await pg.query('select video_id from reparty_private.soundtracks where id=any($1)',[privateState.deck])).rows.map(r=>r.video_id);
 ok(new Set(ids).size===10,'duplicate recordings cannot appear twice');
 ok(!g.answer&&!g.current_id&&!g.deck&&!g.guesses&&!JSON.stringify(g).includes('Sea Shanty'),'public snapshot contains no unrevealed answer or deck');
 await pg.exec('set role authenticated');try{await assert.rejects(pg.exec('select * from reparty_private.soundtracks'),/permission/);await assert.rejects(pg.exec('select * from reparty_private.soundtrack_sessions'),/permission/);await assert.rejects(pg.exec("select reparty_private.soundtrack_view('{}')"),/permission/);checks+=3;}finally{await pg.exec('reset role');}
 await quiz(b,'pause');const loadingRemaining=g.remaining_ms;await quiz(a,'ready');await quiz(b,'ready');ok(g.paused&&g.phase==='loading'&&g.remaining_ms===loadingRemaining,'guest pause freezes loading even when everyone becomes ready');
 await quiz(a,'resume');await quiz(a,'tick');ok(g.phase==='countdown','resume continues ready room');
 await quiz(b,'pause');const countdown=g.remaining_ms;await expire();await quiz(a,'tick');ok(g.paused&&g.phase==='countdown'&&g.remaining_ms===countdown,'paused countdown cannot advance');
 await quiz(b,'resume');await expire();await quiz(a,'tick');ok(g.phase==='guess','guess phase follows server countdown');
 s=await quiz(a,'guess',{answer:'OSRS'});ok(s.quiz_feedback==='correct','OSRS alias scores');
 s=await quiz(a,'guess',{answer:'OSRS'});ok(s.quiz_feedback==='already'&&g.solved.length===1,'duplicate correct guesses cannot score twice');
 s=await quiz(b,'guess',{answer:'Sea Shanty 3'});ok(s.quiz_feedback==='incorrect','wrong track number is rejected');
 await assert.rejects(quiz(b,'guess',{answer:'Sea Shanty 2'}),/moment/);checks++;
 await pg.query(`update reparty_private.soundtrack_sessions set state=state-'guesses' where room_id=$1`,[room]);
 s=await quiz(b,'guess',{answer:'Runescape'});ok(s.quiz_feedback==='correct'&&g.solved.length===2,'versus awards each player independently');
 await quiz(b,'pause',{revision:g.revision-1});const remaining=g.remaining_ms;ok(g.paused,'pause survives another player scoring at the same time');await expire();await quiz(a,'tick');
 await assert.rejects(quiz(a,'guess',{answer:'OSRS'}),/not accepting/);checks++;
 ok(g.paused&&g.remaining_ms===remaining,'paused guess timer is stable across requests');
 await quiz(a,'resume');ok(Math.abs(Date.parse(g.deadline)-Date.now()-remaining)<1000,'resume restores remaining guess time');
 await expire();await quiz(b,'tick');ok(g.phase==='reveal'&&g.answer.title==='Old School RuneScape'&&g.scores[a]===1&&g.scores[b]===1,'reveal awards points once and releases the answer');
 await quiz(a,'tick');ok(g.scores[a]===1,'repeated tick cannot duplicate points');
 ok(g.remaining_ms===10000&&g.reveal_position===15,'reveal lasts ten seconds and continues audio after the guess clip');
 await quiz(b,'pause');await expire();await quiz(a,'tick');ok(g.phase==='reveal'&&g.paused,'answer reveal also pauses for everyone');
 const oldToken=g.token;await quiz(a,'skip');ok(g.phase==='loading'&&g.paused&&g.round===2,'skip while paused preserves room pause');
 s=await quiz(b,'guess',{token:oldToken,answer:'OSRS'});ok(!s.quiz_feedback&&g.solved.length===0,'late answer from previous round is ignored');
 await assert.rejects(quiz(b,'skip'),/host/);checks++;
 const revision=g.revision;s=await quiz(a,'skip',{revision:revision-1});ok(s.quiz_stale&&g.round===2,'stale controls cannot advance twice');
 s=await quiz(a,'exit');ok(s.room.settings.game.mode==='watch'&&JSON.stringify(s.room.playlists)===JSON.stringify(before),'watch playlists survive quiz exit');
 await quiz(a,'enter');ok(g.paused&&g.round===2,'re-enter restores paused session');
 await quiz(a,'reset');await start('teams');await answerPhase();await quiz(a,'guess',{answer:'Sea Shanty 2'});await quiz(b,'guess',{answer:'OSRS'});await quiz(a,'next');ok(g.scores['team-1']===1&&g.scores['team-2']===1,'teams receive independent shared points');
 ok(g.reveal_position>=0&&g.reveal_position<3,'early reveal continues from the current audio position');
 await quiz(a,'reset');await start('group');await answerPhase();await quiz(a,'guess',{answer:'OSRS'});s=await quiz(b,'guess',{answer:'OSRS'});ok(s.quiz_feedback==='already','group answer is shared');await quiz(a,'next');ok(g.scores.group===1,'group receives exactly one point');
 await quiz(a,'skip');await quiz(b,'error');ok(g.phase==='loading','guest playback error does not stop other players');await quiz(a,'error');ok(g.phase==='unavailable'&&g.paused,'host playback error pauses the room safely');await quiz(a,'skip');await quiz(a,'resume');
 for(let n=g.round;n<=g.total;n++)await quiz(a,'skip');ok(g.phase==='finished'&&!g.video_id&&g.scores.group===1,'last round finishes without losing scores');
 await quiz(a,'reset');await start('chill');await answerPhase();
 await quiz(a,'guess',{answer:'OSRS'});ok(g.phase==='guess'&&g.solved.length===1,'first Chill answer does not end the round');
 await quiz(b,'guess',{answer:'OSRS'});await quiz(a,'next');ok(g.scores[a]===1&&g.scores[b]===1&&g.total===null,'Chill awards equal points to every correct player with no round limit');
 const heard=new Set([g.video_id]);let last=g.video_id;
 for(let i=1;i<10;i++){await quiz(a,'skip');heard.add(g.video_id);last=g.video_id;}
 ok(heard.size===10,'Chill plays the whole mix without repeating recordings');
 await quiz(a,'skip');ok(g.round===11&&g.phase==='loading'&&g.video_id!==last&&g.scores[a]===1,'Chill reshuffles endlessly, avoids a boundary repeat and keeps points');
 await quiz(a,'pause');await quiz(a,'ready');await quiz(b,'ready');await expire();await quiz(a,'tick');ok(g.paused&&g.round===11&&g.phase==='loading','Chill shared pause still freezes progression');await quiz(a,'resume');
 await action(c,'join',room);await quiz(c,'join');await quiz(c,'join');ok(g.players.filter(p=>p.id===c).length===1,'late Chill listener joins once without resetting scores');
 await quiz(c,'ready');await quiz(a,'tick');await expire();await quiz(a,'tick');await quiz(c,'guess',{answer:'OSRS'});await quiz(a,'next');ok(g.scores[c]===1&&g.scores[a]===1,'late listener earns their own points');
 for(let i=0;i<101;i++){await quiz(a,'skip');await quiz(a,'next');}
 ok(g.phase==='reveal'&&g.round===112&&g.history.length===100,'long Chill runs keep recent history bounded and never finish');
 await quiz(a,'reset');await start('group');await answerPhase();await quiz(a,'guess',{answer:'OSRS'});await quiz(a,'next');
 await assert.rejects(quiz(b,'takeover'),/still connected/);checks++;
 await pg.query(`update public.reparty_members set last_seen=clock_timestamp()-interval '2 minutes' where room_id=$1 and user_id=$2`,[room,a]);s=await quiz(b,'takeover');ok(g.host===b&&s.room.settings.game.host===b,'remaining player can recover hosting and game-menu controls');
 const matching=await pg.query(`select reparty_private.soundtrack_matches('Runescap','["RuneScape"]') typo,reparty_private.soundtrack_matches('Halo 2','["Halo 3"]') sequel,reparty_private.soundtrack_matches('SOS','["OSRS"]') short,reparty_private.soundtrack_matches('Main Theme','["Old School RuneScape","Sea Shanty 2"]') generic`);
 ok(matching.rows[0].typo&&!matching.rows[0].sequel&&!matching.rows[0].short&&!matching.rows[0].generic,'matching accepts small typos without generic or sequel false positives');
 await pg.exec(migration);ok((await action(b,'snapshot',room)).room.id===room,'migration is safely repeatable');
 const revealUpgrade=fs.readFileSync(root+'/supabase/migrations/20260927030000_reparty_soundtrack_reveal.sql','utf8');await pg.exec(revealUpgrade);await pg.exec(revealUpgrade);ok((await action(b,'snapshot',room)).room.settings.soundtrack.scores.group===1,'reveal upgrade preserves an existing game and scores');
 console.log(`${checks} soundtrack checks passed`);await pg.close();
}
module.exports={setup};if(require.main===module)test().catch(e=>{console.error(e);process.exitCode=1;});
