export const avatarGroups = [
  {
    "key": "animals",
    "label": "Animals",
    "names": [
      "Frog",
      "Panda",
      "Fox",
      "Cat",
      "Dog",
      "Owl",
      "Rabbit",
      "Bear",
      "Deer",
      "Wolf",
      "Otter",
      "Raccoon",
      "Hedgehog",
      "Squirrel",
      "Badger",
      "Red panda",
      "Tiger",
      "Lion",
      "Koala",
      "Penguin",
      "Parrot",
      "Turtle",
      "Axolotl",
      "Bee",
      "Butterfly"
    ]
  },
  {
    "key": "landscapes",
    "label": "Landscapes",
    "names": [
      "Forest cabin",
      "Mountain sunrise",
      "Moonlit lake",
      "Waterfall",
      "Desert dunes",
      "Snowy peak",
      "Tropical island",
      "Autumn woods",
      "Cherry orchard",
      "Volcano",
      "Coastal lighthouse",
      "Floating island",
      "River bridge",
      "Mushroom grove",
      "Starry campsite",
      "Medieval village",
      "Crystal cave",
      "Ocean sunset",
      "Meadow windmill",
      "Ancient ruins",
      "Rainy city",
      "Northern lights",
      "Bamboo forest",
      "Rolling hills",
      "Snowy cottage"
    ]
  },
  {
    "key": "plants",
    "label": "Plants",
    "names": [
      "Sunflower",
      "Red mushroom",
      "Fern",
      "Cactus",
      "Bonsai",
      "Monstera",
      "Lotus",
      "Rose",
      "Lavender",
      "Oak tree",
      "Pine tree",
      "Cherry blossom",
      "Pumpkin",
      "Strawberry",
      "Blueberries",
      "Apple",
      "Acorn",
      "Four leaf clover",
      "Daisy",
      "Orchid",
      "Succulent",
      "Flytrap",
      "Wheat",
      "Chilli plant",
      "Glowing mushroom"
    ]
  },
  {
    "key": "fantasy",
    "label": "Fantasy & MMORPG",
    "names": [
      "Wizard hat",
      "Knight helmet",
      "Dragon head",
      "Crystal staff",
      "Sword and shield",
      "Health potion",
      "Mana potion",
      "Treasure chest",
      "Magic book",
      "Ranger hood",
      "Dwarf helmet",
      "Elven bow",
      "Golden crown",
      "Slime",
      "Phoenix",
      "Unicorn",
      "Griffin",
      "Dungeon doorway",
      "Campfire",
      "Rune stone",
      "Enchanted key",
      "Battle axe",
      "Fairy wings",
      "Mimic chest",
      "Floating spell orb"
    ]
  }
];
export const avatars = avatarGroups.flatMap((g, group) => g.names.map((name, index) => ({ id: group * 25 + index, name, group: g.key })));
