'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Isaac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(html.includes('assets/launchers/moratales-intro.js?v=20260928-2'));
assert(html.includes('assets/launchers/moratales-intro.css?v=20260928-2'));
const button=html.match(/<a\b[^>]*id="openMoratales"[\s\S]*?<\/a>/)[0];
const theme=[...html.matchAll(/<link\b[^>]*rel="stylesheet"[^>]*>/g),...html.matchAll(/<style\b[^>]*>[\s\S]*?<\/style>/g)].map(m=>m[0]).join('');
const fixture=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1">${theme}<link rel="stylesheet" href="/assets/launchers/moratales-intro.css"><style>body{background:#203126;color:white}#openMoratales{display:inline-block}#openMoratales img{width:240px}</style><h1>Launcher check</h1>${button}<script defer src="/assets/launchers/moratales-intro.js"></script>`;
const server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://localhost').pathname;if(rel==='/'){res.writeHead(200,{'Content-Type':'text/html'}).end(fixture);return;}const file=path.resolve(root,'.'+rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}const size=fs.statSync(file).size,m=/bytes=(\d+)-(\d*)/.exec(req.headers.range||''),start=m?+m[1]:0,end=m&&m[2]?Math.min(+m[2],size-1):size-1;const type={'.js':'text/javascript','.css':'text/css','.png':'image/png','.mp4':'video/mp4'}[path.extname(file)]||'application/octet-stream';res.writeHead(m?206:200,{'Content-Type':type,'Content-Length':end-start+1,'Accept-Ranges':'bytes',...(m?{'Content-Range':`bytes ${start}-${end}/${size}`}:{})});fs.createReadStream(file,{start,end}).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,b=await chromium.launch({channel:'msedge',args:['--mute-audio']}),p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));let requests=0;
try{
 await p.route('https://moratales.repocompany.uk/**',r=>r.fulfill({contentType:'text/html',body:'<title>Game loading</title><h1>Game loading</h1>'}));p.on('request',r=>{if(r.url().endsWith('/repo-company-intro.mp4'))requests++;});
 await p.goto(base);assert.equal(requests,0,'film does not download until button is used');
 await p.click('#openMoratales');await p.waitForFunction(()=>{const v=document.querySelector('#moratales-company-intro video');return v&&!v.paused&&v.currentTime>3;});
 const info=await p.locator('video').evaluate(v=>({width:v.videoWidth,height:v.videoHeight,duration:v.duration,inline:v.playsInline}));assert(info.width>0&&info.duration>0&&info.inline);console.log('Video metadata',info);
 fs.mkdirSync(path.join(root,'QA','moratales-intro-captures'),{recursive:true});await p.screenshot({path:path.join(root,'QA/moratales-intro-captures/desktop.png')});
 assert.equal(await p.locator('#moratales-company-intro button').count(),0,'no visible controls');
 assert(await p.locator('#moratales-company-intro').evaluate(d=>{const c=getComputedStyle(d),r=d.getBoundingClientRect();return c.borderTopWidth==='0px'&&c.paddingTop==='0px'&&c.boxShadow==='none'&&c.outlineStyle==='none'&&r.x===0&&r.y===0&&r.width===innerWidth&&r.height===innerHeight;}),'borderless full viewport under the real website theme');
 await p.waitForURL('https://moratales.repocompany.uk/',{timeout:Math.ceil(info.duration*1000)+15000});assert.equal(await p.title(),'Game loading');console.log('PASS natural completion opens the existing game URL');
 await p.goBack();await p.waitForSelector('#openMoratales');assert.equal(await p.locator('#moratales-company-intro[open]').count(),0);await p.click('#openMoratales');await p.keyboard.press('Escape');await p.waitForURL('https://moratales.repocompany.uk/');
 await p.goto(base);await p.click('#openMoratales');await p.keyboard.press('Escape');await p.waitForURL('https://moratales.repocompany.uk/');console.log('PASS Back, replay, skip and Escape');
 await p.route('**/repo-company-intro.mp4',r=>r.abort());await p.goto(base);await p.click('#openMoratales');await p.waitForURL('https://moratales.repocompany.uk/');await p.unroute('**/repo-company-intro.mp4');console.log('PASS failed video does not block entry');
 await p.setViewportSize({width:390,height:844});await p.goto(base);await p.click('#openMoratales');await p.waitForFunction(()=>document.querySelector('video').currentTime>3);await p.screenshot({path:path.join(root,'QA/moratales-intro-captures/mobile.png')});assert(await p.locator('dialog').evaluate(d=>d.scrollWidth<=innerWidth&&d.scrollHeight<=innerHeight+1));await p.keyboard.press('Escape');await p.waitForURL('https://moratales.repocompany.uk/');
 // Simulate a stalled download with the actual watchdog accelerated only in this test.
 await p.addInitScript(()=>{const original=setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms===12000?100:ms,...args);HTMLMediaElement.prototype.play=function(){return new Promise(()=>{});};});await p.goto(base);await p.click('#openMoratales');await p.waitForURL('https://moratales.repocompany.uk/');assert.deepEqual(errors,[]);console.log('PASS mobile layout, stall fallback and no browser errors');
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
